### PR TITLE
True false usage for export

### PR DESCRIPTION
**Pull request by Abdelghani90**
@haffo @jperugini #735

### CODE REVIEW

**Comment by haffonist** [comment]
@Abdelghani90 This does not seem to be related to just the issue #773. I can't validate this easily without your help. 
Please stop by and we can go over the changes before I merge. 

Thanks

**Comment by Abdelghani90** [comment]
I have fixed some issues for the datatype Library too. but I am modifying every thing. so it doesn't matter if i loose this code.

**Comment by haffonist** [comment]
Can you do a pull request on just the issue #773 then or do you prefer that we validate the datatype Library stuff as well ?

________________________________

**Comment by Abdelghani90** [comment]
don't worry about the datatype library. This code will not be used anymore. It was a temporary fix

**Pull request merged**
